name: Release and Deploy

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  release-please:
    if: github.event_name == 'push'
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        with:
          release-type: go
          token: ${{ steps.app-token.outputs.token }}

  build-and-deploy:
    if: github.event_name == 'release'
    uses: s12labs/.github/.github/workflows/reusable-docker-build.yml@main
    with:
      app_name: ${{ github.event.repository.name }}
    secrets: inherit

  update-gitops:
    needs: build-and-deploy
    uses: s12labs/.github/.github/workflows/reusable-gitops-update.yml@main
    with:
      app_name: ${{ github.event.repository.name }}
      image_tag: ${{ github.event.release.tag_name }}
      bootstrap_if_missing: true
    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
